export const GET_USEREVENTS_SUCCESS = "GET_USEREVENTS_SUCCESS";
export const GET_USEREVENTS_FAILED = "GET_USEREVENTS_FAILED";
export const GET_USEREVENTS_PENDING = "GET_USEREVENTS_PENDING";

export const ADD_USEREVENT_SUCCESS = "ADD_USEREVENT_SUCCESS";
export const ADD_USEREVENT_FAILED = "ADD_USEREVENT_FAILED";
export const ADD_USEREVENT_PENDING = "ADD_USEREVENT_PENDING";

export const DELETE_USEREVENT_SUCCESS = "DELETE_USEREVENT_SUCCESS";
export const DELETE_USEREVENT_FAILED = "DELETE_USEREVENT_FAILED";
export const DELETE_USEREVENT_PENDING = "DELETE_USEREVENT_PENDING";