
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('user-events').del()
    .then(function () {
      // Inserts seed entries
      return knex('user-events').insert(
        [{
          "user_id": 21,
          "event_id": 40
        }, {
          "user_id": 45,
          "event_id": 41
        }, {
          "user_id": 40,
          "event_id": 28
        }, {
          "user_id": 21,
          "event_id": 77
        }, {
          "user_id": 39,
          "event_id": 35
        }, {
          "user_id": 14,
          "event_id": 59
        }, {
          "user_id": 46,
          "event_id": 24
        }, {
          "user_id": 18,
          "event_id": 79
        }, {
          "user_id": 34,
          "event_id": 3
        }, {
          "user_id": 15,
          "event_id": 98
        }, {
          "user_id": 21,
          "event_id": 69
        }, {
          "user_id": 20,
          "event_id": 69
        }, {
          "user_id": 7,
          "event_id": 100
        }, {
          "user_id": 31,
          "event_id": 85
        }, {
          "user_id": 3,
          "event_id": 79
        }, {
          "user_id": 46,
          "event_id": 89
        }, {
          "user_id": 4,
          "event_id": 90
        }, {
          "user_id": 7,
          "event_id": 41
        }, {
          "user_id": 25,
          "event_id": 72
        }, {
          "user_id": 50,
          "event_id": 10
        }, {
          "user_id": 13,
          "event_id": 14
        }, {
          "user_id": 28,
          "event_id": 3
        }, {
          "user_id": 7,
          "event_id": 63
        }, {
          "user_id": 20,
          "event_id": 3
        }, {
          "user_id": 3,
          "event_id": 44
        }, {
          "user_id": 10,
          "event_id": 7
        }, {
          "user_id": 16,
          "event_id": 66
        }, {
          "user_id": 42,
          "event_id": 3
        }, {
          "user_id": 24,
          "event_id": 55
        }, {
          "user_id": 30,
          "event_id": 25
        }, {
          "user_id": 8,
          "event_id": 40
        }, {
          "user_id": 11,
          "event_id": 1
        }, {
          "user_id": 49,
          "event_id": 1
        }, {
          "user_id": 50,
          "event_id": 26
        }, {
          "user_id": 29,
          "event_id": 46
        }, {
          "user_id": 34,
          "event_id": 60
        }, {
          "user_id": 11,
          "event_id": 48
        }, {
          "user_id": 50,
          "event_id": 12
        }, {
          "user_id": 7,
          "event_id": 27
        }, {
          "user_id": 2,
          "event_id": 66
        }, {
          "user_id": 6,
          "event_id": 35
        }, {
          "user_id": 50,
          "event_id": 42
        }, {
          "user_id": 29,
          "event_id": 41
        }, {
          "user_id": 31,
          "event_id": 27
        }, {
          "user_id": 23,
          "event_id": 67
        }, {
          "user_id": 8,
          "event_id": 20
        }, {
          "user_id": 9,
          "event_id": 74
        }, {
          "user_id": 24,
          "event_id": 90
        }, {
          "user_id": 17,
          "event_id": 10
        }, {
          "user_id": 48,
          "event_id": 67
        }, {
          "user_id": 6,
          "event_id": 84
        }, {
          "user_id": 1,
          "event_id": 1
        }, {
          "user_id": 3,
          "event_id": 47
        }, {
          "user_id": 39,
          "event_id": 29
        }, {
          "user_id": 26,
          "event_id": 79
        }, {
          "user_id": 31,
          "event_id": 72
        }, {
          "user_id": 38,
          "event_id": 96
        }, {
          "user_id": 10,
          "event_id": 57
        }, {
          "user_id": 46,
          "event_id": 20
        }, {
          "user_id": 6,
          "event_id": 48
        }, {
          "user_id": 30,
          "event_id": 38
        }, {
          "user_id": 35,
          "event_id": 82
        }, {
          "user_id": 13,
          "event_id": 88
        }, {
          "user_id": 26,
          "event_id": 18
        }, {
          "user_id": 30,
          "event_id": 54
        }, {
          "user_id": 41,
          "event_id": 48
        }, {
          "user_id": 46,
          "event_id": 33
        }, {
          "user_id": 46,
          "event_id": 44
        }, {
          "user_id": 43,
          "event_id": 81
        }, {
          "user_id": 23,
          "event_id": 36
        }, {
          "user_id": 33,
          "event_id": 51
        }, {
          "user_id": 38,
          "event_id": 7
        }, {
          "user_id": 34,
          "event_id": 83
        }, {
          "user_id": 1,
          "event_id": 25
        }, {
          "user_id": 3,
          "event_id": 64
        }, {
          "user_id": 11,
          "event_id": 68
        }, {
          "user_id": 2,
          "event_id": 91
        }, {
          "user_id": 45,
          "event_id": 18
        }, {
          "user_id": 25,
          "event_id": 61
        }, {
          "user_id": 31,
          "event_id": 50
        }, {
          "user_id": 23,
          "event_id": 70
        }, {
          "user_id": 29,
          "event_id": 12
        }, {
          "user_id": 23,
          "event_id": 69
        }, {
          "user_id": 11,
          "event_id": 99
        }, {
          "user_id": 27,
          "event_id": 81
        }, {
          "user_id": 20,
          "event_id": 58
        }, {
          "user_id": 39,
          "event_id": 77
        }, {
          "user_id": 39,
          "event_id": 5
        }, {
          "user_id": 16,
          "event_id": 18
        }, {
          "user_id": 43,
          "event_id": 34
        }, {
          "user_id": 32,
          "event_id": 79
        }, {
          "user_id": 40,
          "event_id": 78
        }, {
          "user_id": 36,
          "event_id": 54
        }, {
          "user_id": 44,
          "event_id": 61
        }, {
          "user_id": 2,
          "event_id": 85
        }, {
          "user_id": 37,
          "event_id": 8
        }, {
          "user_id": 28,
          "event_id": 92
        }, {
          "user_id": 18,
          "event_id": 76
        }, {
          "user_id": 17,
          "event_id": 33
        }, {
          "user_id": 33,
          "event_id": 35
        }]
      );
    });
};
