export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILED = "GET_EVENTS_FAILED";
export const GET_EVENTS_PENDING = "GET_EVENTS_PENDING";

export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILED = "ADD_EVENT_FAILED";
export const ADD_EVENT_PENDING = "ADD_EVENT_PENDING";

export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILED = "UPDATE_EVENT_FAILED";
export const UPDATE_EVENT_PENDING = "UPDATE_EVENT_PENDING";

export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";
export const DELETE_EVENT_PENDING = "DELETE_EVENT_PENDING";